import StrokeCapRound from "./StrokeCapRound";
import StrokeCapSquare from "./StrokeCapSquare";
import StrokeCapButt from "./StrokeCapButt";
import StrokeJoinRound from "./StrokeJoinRound";
import StrokeJoinBevel from "./StrokeJoinBevel";
import StrokeJoinMiter from "./StrokeJoinMiter";
import NodeAdd from "./NodeAdd";
import NodeRemove from "./NodeRemove";
import NodeStraight from "./NodeStraight";
import NodeCurve from "./NodeCurve";
import Text from "./Text";
import Layout from "./Layout";
import Symmetry from "./Symmetry";
import LogoCentrix from "./LogoCentrix";
import LogoTop from "./LogoTop";
import LogoLeft from "./LogoLeft";
import LogoBottom from "./LogoBottom";
import LogoRight from "./LogoRight";
import CircleShape from "./CircleShape";
import LineShape from "./LineShape";
import RectangleShape from "./RectangleShape";
import TriangleShape from "./TriangleShape";
import RhombusShape from "./RhombusShape";
import PentagonShape from "./PentagonShape";
import HexagonShape from "./HexagonShape";
import AlignLeft from "./AlignLeft";
import AlignCenter from "./AlignCenter";
import AlignRight from "./AlignRight";
import ZoomPlus from "./ZoomPlus";
import ZoomMinus from "./ZoomMinus";
import SelectTemplate from "./SelectTemplate";
import Template3Sides from "./Template3Sides";
import Template4Sides from "./Template4Sides";
import Template6Sides from "./Template6Sides";
import Template8Sides from "./Template8Sides";
class Icons {}
Icons.StrokeCapRound = StrokeCapRound;
Icons.StrokeCapSquare = StrokeCapSquare;
Icons.StrokeCapButt = StrokeCapButt;
Icons.StrokeJoinRound = StrokeJoinRound;
Icons.StrokeJoinBevel = StrokeJoinBevel;
Icons.StrokeJoinMiter = StrokeJoinMiter;
Icons.NodeAdd = NodeAdd;
Icons.NodeRemove = NodeRemove;
Icons.NodeStraight = NodeStraight;
Icons.NodeCurve = NodeCurve;
Icons.Text = Text;
Icons.Layout = Layout;
Icons.Symmetry = Symmetry;
Icons.LogoCentrix = LogoCentrix;
Icons.LogoTop = LogoTop;
Icons.LogoLeft = LogoLeft;
Icons.LogoBottom = LogoBottom;
Icons.LogoRight = LogoRight;
Icons.CircleShape = CircleShape;
Icons.LineShape = LineShape;
Icons.RectangleShape = RectangleShape;
Icons.TriangleShape = TriangleShape;
Icons.RhombusShape = RhombusShape;
Icons.PentagonShape = PentagonShape;
Icons.HexagonShape = HexagonShape;
Icons.AlignLeft = AlignLeft;
Icons.AlignCenter = AlignCenter;
Icons.AlignRight = AlignRight;
Icons.ZoomPlus = ZoomPlus;
Icons.ZoomMinus = ZoomMinus;
Icons.SelectTemplate = SelectTemplate;
Icons.Template3Sides = Template3Sides;
Icons.Template4Sides = Template4Sides;
Icons.Template6Sides = Template6Sides;
Icons.Template8Sides = Template8Sides;
export default Icons;
